service: mabel
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.10
  stage: production
  region: eu-west-2
  environment:
    FIREBASE_PROJECT_ID: ${ssm:mabel-firebase-project-id}
    FIREBASE_PRIVATE_KEY_ID: ${ssm:mabel-firebase-private-key-id}
    FIREBASE_PRIVATE_KEY: ${ssm:mabel-firebase-private-key}
    FIREBASE_CLIENT_EMAIL: ${ssm:mabel-firebase-client-email}
    FIREBASE_CLIENT_ID: ${ssm:mabel-firebase-client-id}
    SLACK_BOT_TOKEN: ${ssm:mabel-slack-bot-token}
    SLACK_SIGNING_SECRET: ${ssm:mabel-slack-signing-secret}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: ${ssm:mabel-lambda-slack-arn}
functions:
  hello:
    handler: handler.hello
  slack:
    handler: src/handlers/slack/slack.handler
    events:
      - http:
          path: slack/events
          method: post
          cors: true
plugins:
  - serverless-python-requirements
